# ============================================================
# 🧠 ChroniLog Configuration
# Place this file at the root of your project directory.
# This controls default behavior for ChroniLog logging.
# ============================================================

[logging]

# Logging level: DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
# Default: "INFO"
level = "DEBUG"
log_format = "default"  # Options: default, json

# Sentry
enable_sentry = false
sentry_dsn = "https://<your_public_key>@o123456.ingest.sentry.io/1234567"
sentry_level = "ERROR"
sentry_traces_sample_rate = 0.0

# Whether to also output logs to the console
# Default: false (file-only unless overridden)
enable_console = false

# File path for the primary log file
# Default: "logs/app.log" — this can be overridden per logger
log_path = "logs/chronilog.log"

# Automatically fallback to emoji-safe ASCII replacements
# Useful on terminals that can’t print Unicode emojis
emoji_fallback = true

# Whether to wipe the log file on every app launch (use with caution)
wipe_log_on_startup = false

# Maximum size of log file before it rolls over (in bytes)
max_log_file_size = 1048576  # 1 MB

# Maximum number of backup log files to retain
backup_count = 3

# Format of timestamps in the log output
timestamp_format = "%Y-%m-%d %H:%M:%S"

# Optional global format override (use logging format syntax)
# If omitted, ChroniLog uses its internal formatting with emoji and rich
# log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Set this to true to disable all color/rich formatting (file-safe plain output)
disable_rich_format = false

# Optional: Only log messages that match this module prefix

# Enable log rotation (requires max_log_file_size and backup_count)
enable_rotation = true

# Console log output stream: "stdout" or "stderr"
console_output = "stdout"

